import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/shared/header/Header";
import Footer from "@/components/shared/footer/Footer";
import {Providers} from '@/redux/Provider.redux'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <Providers >
        <Header/>
        {children}
        <Footer/>
        </Providers>
        </body>
    </html>
  );
}
